language: python

# turn off sudo
sudo: true

# python versions to be tested
matrix:
  include:
    - python: 3.6
    - python: 3.7

# will still build pull requests
branches:
  only:
    - master

notifications:
    email: false

before_install:

# Get local information about the machine
  - uname -a
  - free -m
  - df -h
  - ulimit -a

services:
  - mysql

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # Install the library with test requirements
  - conda install -c conda-forge numpy pandas
  - conda install -c openbabel openbabel
  - pip install flask
  - pip install flask-mysql
  - pip install pymysql
  - pip install numpydoc
  - pip install -e .[tests]
  - pip install codecov

script:
  - pytest -v --cov=chembddb tests
  # with doctest to test examples in doctrings
#  - pytest -v --doctest-modules --cov=./

# if successful, track code coverage with codecov
after_success:
  - codecov
