name: chembddb
channels:
    - conda-forge
    - openbabel

dependencies:
    - python=3.7
    - pip
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - nbsphinx

      # chembddb depends
    - openbabel
    - rdkit
    
    - pip:
      - flask
      - flask-mysql
      - numpy
      - pandas
      - pymysql
© 2019 GitHub, Inc.